### ISSUE TITLE
Bug - unexpected panic

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#123]
[panic.zip](https://github.com/homotopy-io/homotopy-rs/files/6855499/panic.zip)
 
Homotopy in S19 causes panic.
<img width="754" alt="Screenshot 2021-07-21 at 13 08 34" src="https://user-images.githubusercontent.com/35509721/126486232-6e1b978e-d483-42e8-a1e3-6ad006949f13.png">

**Comment by NickHu** [comment]
This is not a panic. I believe that the code isn't even buggy here, it's just horrendously slow - or rather, the algorithm we are using isn't fast enough.

During expansion, factorization is called, which initialises a `MonotoneSequences` iterator of length 20, with max value 18:
`MonotoneSequences::new(20, 18)`.

The monotone sequence is a guess for the underlying monotone of the factorization rewrite being constructed, and the number of sequences which exist for these parameters is 38 C 18 = 33578000610 ( (length 20 array, each value can range 0-18 --- monotonicity means that counting this is equivalent to describing where the initial segment of zeroes ends, the second segment of 1s ends, etc... equivalent to the number of ways 18 bars can be placed between 20 digits, i.e. (20 + 18) choose 18).

I think we need to be smarter about iterating through all of these, because this number seems too large. The current implementation is to iterate through all possible monotone sequences lexicographically. Any ideas @jamievicary?

**Comment by zrho** [comment]
We could try to make the search smart enough to only iterate over monotones
that compose properly, i.e. that aren't rejected by the first check in the
factorisation thing. This means that we only consider those assignments of
h(i) which are in the preimage g^{-1}(f(i)) when we try to find h s.t.
h(g(i)) = f(i); since g is monotone, that preimage is an interval, so we
could try iterating over the cartesian product of these intervals.

**Comment by zrho** [comment]
*h such that g(h(i)) = f(i).

**Comment by NickHu** [comment]
Cartesian product of what exactly? Each interval of the preimage of g?

**Comment by zrho** [comment]
Yeah, so we need a value of h(i) for every i in the domain. Through the
requirement that g(h(i)) = f(i) we know that h(i) must be in the interval
g^{-1}(f(i)). Naively we could search for assignments of h(i) restricted to
those intervals each, and filter for monotonous sequences. A bit less
naively we could integrate this with the monotone iteration thing.

**Comment by jamievicary** [comment]
Agrees. The space of possibly-valid monotones is much smaller and quite
easy to describe I think.

**Comment by zrho** [comment]
Another optimisation could arise from this: when the recursive
factorisation fails in the case that h(i) = j for some h, then it also
fails for all other h' with h'(i) = j. Accounting for this might avoid a
lot of churn.

**Comment by NickHu** [comment]
I believe I have fixed this in 9112364. It's essentially Lukas's suggestion to search for the underlying monotone by looking in the preimage of $g$. There's no caching, as it seems fast enough now: the expansion move at the head of this issue is now near instant, but strangely I need to do it twice before it visually shows up. I have confirmed that the first drag does a successful expansion, and so does the second, but for some reason the first one doesn't visually cause the diagram to change. I think it's a consequence of only looking at this 2D projection.

**Comment by jamievicary** [comment]
That's excellent Nick thank you. Hao do you agree the issue is resolved?

Your last point about the display not updating is weird. I don't see why
that would be to do with the 2d projection. Does the first interaction
actually change the global diagram?

**Comment by jamievicary** [comment]
This looks fine to me. The global diagram does indeed update with your fix after doing the homotopy once. The reason that the view does not update properly is a manifestation of issue #30. So I think this can be closed.
