### ISSUE TITLE
Check a diagram is well-formed before importing it

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#154]

**Comment by jamievicary** [comment]
Calin this is great!

I think we also need something (as a run-time "debug mode" option) that checks if every diagram ever built is well-formed. Otherwise we will keep encountering similar situations, where bugs in diagram construction routines (e.g. contraction) produce malformed diagrams, in a way that may not be picked up, or may later manifest as an error in typechecking/normalization, whereas in fact the error is elsewhere. Does that make sense?

**Comment by calintat** [comment]
That's what I'm doing in #156.
