### ISSUE TITLE
Update selected slice path when manipulating the diagram

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#30]
Certain manipulations such as attachment and homotopies should change the path of the currently selected slice.

**Comment by jamievicary** [comment]
I remember finding this exceptionally tricky, and in fact I think it's still not right in the JS implementation. In particular imagine you're deep inside a slice of a slice of a slice etc of your diagram, and you perform a mouse action to insert a half-braid. What this really does is inserts a "half braid creation, half braid removal bubble" in the middle of your diagram. But since the user has performed the mouse action to create a half-braid, what she wants to see is the result of that, i.e. the half-braid, so you need to make sure to update the slices to navigate to that. For some reason, I found it difficult to compute in general what those slices are.

Extra complexities for this will be added when we have invertible generators, since that requires a new ability to insert "creation-annihilation bubbles" for every generator.

**Comment by jamievicary** [comment]
Calin is working on this now.
