### ISSUE TITLE
Deserialisation issue

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#303]
This seems to no longer deserialise:
[filename_todo.29.zip](https://github.com/homotopy-io/homotopy-rs/files/7753997/filename_todo.29.zip)

**Comment by NickHu** [comment]
As I determined in #59, it appears that this broke a long time ago (actually, on the same day that issue was posted). We started versioning file formats beginning September 1st. I think I understand why this doesn't import anymore, and it's not an easy fix. I think it's reasonable to just close this issue.
