### ISSUE TITLE
Grey out UI operations in the bottom left when they're not legal

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#40]
This is a feature of the JS version which people find very useful. It's trivial to determine in the majority of cases whether an operation is currently valid.

**Comment by NickHu** [comment]
This was implemented in 993c451d57c2dc5d4a0032b96267590081875b9b. I opted for making the buttons invisible instead of graying out, because it seemed visually cleaner to me. Non-visible buttons still occupy the same space they would otherwise occupy, so muscle memory can be preserved when using touch devices.
