### ISSUE TITLE
Intercept browser back and forward buttons for undo and redo

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#46]
Perhaps impossible, I'm not sure.

**Comment by NickHu** [comment]
Modern browsers don't allow you to intercept back and forward with custom event handlers (because it would be used by spam websites). I think the most you can do is display a browser built-in warning when trying to leave (#47)

**Comment by jamievicary** [comment]
Could you just remind me why we don't want to serialize the state with every interaction and push it onto the session history.

**Comment by NickHu** [comment]
Because it's slow. Even if you did that, you can't modify the session history because it's read-only. The most you could do is add buttons in the UI which behave the same way as browser back/forward, but not change this behaviour. See [here](https://developer.mozilla.org/en-US/docs/Web/API/History_API) for more details.

**Comment by jamievicary** [comment]
OK. How long does it take to serialize the state for a realistically large
scenario?
