### ISSUE TITLE
Slight adjustment to control points for 2d renderer

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#473]
I would like us to make some minor tweaks to the bezier control parameters, Calin maybe we can do this together some time in person.

**Comment by calintat** [comment]
Sure, what kind of tweaks did you have in mind?

The nice thing is whatever changes we make will also be reflected in the Tikz export.

**Comment by jamievicary** [comment]
Yes I agree that is a nice feature. I haven't collected my thoughts on this
yet, I will do that soon and we can discuss in person.

**Comment by jamievicary** [comment]
Hi Chiara thanks for this. I loaded the example you sent in the version hosted by the PR, I agree it looks nice, but I'm not sure what it looked like before. Also, Calin and I already worked on this a couple of weeks ago and I thought we fixed it, if there are further issues could you attach screenshots please?

**Comment by calintat** [comment]
The main different between this PR and master is that full braids now have a nearly horizontal tangent to distinguish them from algebraic points.

**Comment by regular-citizen** [comment]
The current version:

![CopyQ pwmrtF](https://user-images.githubusercontent.com/7887982/187235474-34c96e64-e1ff-4a8a-8b11-6e7d5eb0051d.png)

The new version:

![CopyQ fCuLtz](https://user-images.githubusercontent.com/7887982/187235348-a272ecff-ee53-4b30-b808-6aac68edbfca.png)

**Comment by regular-citizen** [comment]
I can make it less sloped, but that is precisely the change.

**Comment by jamievicary** [comment]
How can it be more horizontal than fully horizontal?? Sorry I am totally confused...

**Comment by calintat** [comment]
> How can it be more horizontal than fully horizontal?? Sorry I am totally confused...

Haha sorry I mean the slope is closer to being a horizontal line than a vertical one (i.e. the angle is less than 45 degrees).

**Comment by regular-citizen** [comment]
Base example:
![CopyQ CNsbba](https://user-images.githubusercontent.com/7887982/187239949-eb3676e6-9d5f-41ed-9bba-334134c0c154.png)

90% horizontal:
![CopyQ MvqzOU](https://user-images.githubusercontent.com/7887982/187240066-365e83bd-2931-4c62-a89e-14feeb7186d1.png)

80% horizontal:
![CopyQ idIngN](https://user-images.githubusercontent.com/7887982/187241068-f11271e7-1daa-412e-ae72-8201d53c3693.png)

Old one was 60% horizontal. Opinions? I'm veering for a 85% horizontal solution.

**Comment by jamievicary** [comment]
I think I might prefer 95% ... so maybe we can compromise and go for 90%?

**Comment by calintat** [comment]
I am happy with 90%.

**Comment by doctorn** [comment]
90 looks really cool!

**Comment by regular-citizen** [comment]
90% it is.

**Comment by jamievicary** [comment]
Thank you all glad to see such strong engagement with this critical issue :)

**Comment by calintat** [comment]
Chiara can you make sure it works correctly on this example:

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/187243103-afa9475a-10f5-41bb-8c0b-e60057d2d93b.svg)
[homotopy_io_export.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/9446055/homotopy_io_export.hom.zip)

The two wires should have the same tangent, otherwise they will not join up correctly.

**Comment by regular-citizen** [comment]
Oh sorry about that, should be a quick fix.

**Comment by regular-citizen** [comment]
So, turns out it was not a quick fix, and the idea of using sloped tangents is fundamentally flawed.
The reason is that we may make braids arbitrarily wide, and to keep the tangent angle fixed, it will eventually cause one of the control points to be above the endpoint. This is the visual result:

![image](https://user-images.githubusercontent.com/7887982/187395247-96b95bba-2dd7-40bc-ba61-ed4c09201ac6.png)

We discussed this with @calintat, and the solution we will adopt is to using horizontal tangents, but make the horizontal control point closer than the vertical one:
![image](https://user-images.githubusercontent.com/7887982/187395845-45d3e16c-ec7f-4047-8952-1a603343e86d.png)

**Comment by regular-citizen** [comment]
The above approach does not produce any meaningful difference in the output, compared to the current beta. I'm not changing the current version and closing the issue.
