### ISSUE TITLE
Another contraction bug

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#49]
Here dragging the purple dot upwards causes a panic. However, the contraction should be valid.
[filename_todo (22).zip](https://github.com/homotopy-io/homotopy-rs/files/6353534/filename_todo.22.zip)

**Comment by zrho** [comment]
Apparently there was more than one bug that caused this issue, and while my commit fixed my minimal test example it did not fix this.

**Comment by jamievicary** [comment]
Great! It would be fun to hear what the issues were if you don't mind
sharing.

**Comment by zrho** [comment]
The bug was in rewrite composition again. In the case that the target of a
cone in the first rewrite and the source of a cone in the second rewrite
overlap, the offset computation needed to be delayed so that it is applied
to the following cones but not the current one. I've added a randomised
test that would have caught this and didn't find any more errors after the
fix.

**Comment by jamievicary** [comment]
Ah I see. I genuinely think the rewrite composition was one of the hardest
things to write in the JS version. I suspect your nice recursive version is
much better.
