### ISSUE TITLE
Cones becoming trivial

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#53]
Not really an issue, more a point of discussion.

A subtle point that I recall from the JS version was that sometimes a cone can *become* trivial, and this has to be checked for, and the cone deleted if this happens (since of course in the sparse representation we don't encode trivial cones.)

I wonder if Lukas or Nick recognize this phenomenon, and if this check is performed as appropriate in the rust implementation.

A debugging check that could be inserted when creating a cone is that it is not trivial. This would be good to check at least during development that we're not creating trivial cones at runtime. (Where trivial means that the source slices array has length 1, and the subrewrite is an identity.)

**Comment by zrho** [comment]
In `RewriteN::new` we filter out all trivial cones. The check if a cone is trivial is shallow, but because we simplify rewrites at the point of creation it should catch all cases of trivial cones. I’m closing this issue since we’re already doing the proposed optimization, but feel free to reopen it if it turns out that it’s not working somewhere.

**Comment by jamievicary** [comment]
Excellent
