### ISSUE TITLE
Performance issue with high-dimensional contraction

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#55]
Now that contraction is working really well I've been able to construct some high-dimensional composites. I've rapidly run into a performance issue. Here is the identical scenario constructed in both the js and rs versions:
[scenarios.zip](https://github.com/homotopy-io/homotopy-rs/files/6370815/scenarios.zip)

If you try performing the same contraction in both scenarios, you will notice that the rs version is much slower. As you go up dimension the problem gets much worse. In low dimension the rs version is much faster; this is only an issue that appears in these high-dimensional scenarios.

It would be great to investigate why this is happening. I have profiled both in Chrome, in both cases contracting the top vertex downwards. In rs this took 7.96s, while in js this took 2.15s. Looking at the traces, one sees that the rs version has many hashconsing-related calls. Maybe this is the issue?

**Comment by zrho** [comment]
I've profiled this contraction and most of the time seems to be inside the normalisation procedure. I had recently removed an optimisation from normalisation because it was not quite sound in the original form, but not doing the early return when there is an identity in the sink might have caused this. I will look at it more closely tomorrow.

<img width="1074" alt="profiling-contraction" src="https://user-images.githubusercontent.com/357669/115975489-75b4df80-a565-11eb-979e-d3956bcc2bcc.png">

**Comment by zrho** [comment]
472f1a2 should have made this a lot faster, but still not to an acceptable level. The code spends a lot of time on hash consing and even switching out the hasher for a faster one yields only marginal improvements. There are possible improvements like caching the maximum dimensional generator (see #57), but ultimately hash consing as it is appears to be a big performance problem.

**Comment by zrho** [comment]
With 39f465c normalisation has almost vanished from the profile. Now the big remaining parts are the calculation of the maximum dimensional generator and type checking, both of which seem to consist to a large part of hashconsing overhead. At least the generator calculation can still be optimised.

**Comment by jamievicary** [comment]
Great, this is a lot better than before. But I think it's still disappointingly slow.

One possibility is to switch to the hashconsing method adopted by the JS version, where we just create ordinary non-hashconsed objects during intensive procedures like contraction or typechecking, and then deduplicate at the end after the UI interaction has completed and the display has been updated. That way the deduplication work takes place unnoticed to the user.

**Comment by zrho** [comment]
Commit e37dfbea4dbdc6c79134653a7ffeab95580309e4 optimises the calculation of the maximum-dimensional generator so that it does not allocate at all. In Firefox on my machine the contraction now takes around 150ms whereas the javascript version takes 1s. The most significant remaining cost center is type checking, primarily through allocating and hashconsing the restricted diagrams. Even if hashconsing was entirely free it looks like type checking would still remain the dominant cost here.

**Comment by jamievicary** [comment]
This is fantastic progress. I think we can consider this closed for now and revisit in future as necessary.
