### ISSUE TITLE
Attachment logic not quite correct for identity diagrams

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#617]
Suppose you have a signature with 2 1-cells, and 1 2-cell between them, looking like this:
![image](https://user-images.githubusercontent.com/450276/180846818-59a8af76-842f-4d58-8abe-dcc68d0df864.png)

Then this 2-cell can be used as a rewrite between the 1-cells like so:
![image](https://user-images.githubusercontent.com/450276/180846959-719f4083-5817-42c5-a2fa-a3bd5307e2c9.png) ↝ ![image](https://user-images.githubusercontent.com/450276/180847120-390abcae-2668-4bab-8255-cd2e50464bf3.png)
and indeed if you click on the red dot, the system recognises this and applies the 2-cell.

However, in the attached workspace, where there is a single 0-cell $x$, and a 3-cell from $\text{id} (\text{id} (x))$ to a bubble (i.e. a 3D cup), attachment does not behave the same way; no matter where you click, starting with $\text{id} (\text{id} (x))$ does not allow the 3-cell to be attached.
[3d_cup.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/9183878/3d_cup.hom.zip)

**Comment by calintat** [comment]
The problem here is that if you start with $id(id(x))$, it has singular height 0 so there is no way to click in the interior of the diagram, because every click gets treated as if it was on the boundary. We should fix that. It's somewhat related to #567.

In the meantime, you could get around that by taking identity and attaching in the target,

**Comment by calintat** [comment]
@regular-citizen You could also have a go at this if you want, it's a bit more complicated though as it involves understanding obscure Lukas code.
