### ISSUE TITLE
4d braid

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#710]
I made two 3d scalars and then created a 4d diagram where one scalar does a full loop around the other one. I have two problems then:

1. I should be able to contract this braid to the identity, since it is in four dimensions. When I try it says "contraction ambiguous". 
2. In the video rendering of this 4d diagram, the initial and final positions of the two dots in 3d space are not the same. I think they should be, since the 4d diagram has same source and target

[4dbraid.zip](https://github.com/homotopy-io/homotopy-rs/files/9375098/4dbraid.zip)
.

**Comment by jamievicary** [comment]
I think this is correct. The contraction is ambiguous because there are two variants, the left and right syllepsis, you have to choose a different move which selects one of them specifically.

Regarding the layout, I think the layout algorithm may make global layout choices which can result in source and target having different layouts even if they are the same diagram.

**Comment by mlharaujo** [comment]
Yes, that's a good point. Is there an easy way to construct these two different syllepsis in homotopyio?

**Comment by jamievicary** [comment]
Yes you have to go into an appropriate subslice where you can do the
necessary contraction to break the symmetry.

**Comment by mlharaujo** [comment]
Thanks, I will try that!

**Comment by calintat** [comment]
Is it okay to close this?

**Comment by mlharaujo** [comment]
Yes.
