### ISSUE TITLE
3D System Architecture

### ISSUE THREAD

**Issue by Akvile1206** [homotopy-io/homotopy-rs#91]
There should be three main parts responsible for rendering 3D and 4D homotopies: the cubicaliser; the subdivider; the renderer. This post describes how they can interact with the existing project:

1. The Cubicaliser given an n-diagram object would apply Calin's algorithm to build an n-dimensional cubical mesh for subdivision. The cubical mesh could be a simple list of n-cubes where each vertex is tagged with appropriate generators. The implementation could logically be part of both `homotopy-core` or `homotopy-graphics`.
2. The Subdivider takes a list of cubes provided by the Cubicaliser, subdivision parameters (number of steps for instance) and computes the smooth mesh scene for 3D case or scenes for 4D case. Probably should be part of `homotopy-graphics` module. 
3. The Renderer could be split into two parts diagram3d.rs and diagram4d.rs that would reuse similar methods to render a scene in the web browser and allow the user to interact with it. It should probably be a part of `homotopy-web` module as it will reference an HTML canvas object or similar. In addition, it would also take a scene description (triangle mesh) for 3D case or a collection of scenes for 4D case generated by the Subdivider component.

Each of these classes will expose only one or two key methods.

Other new supporting classes:
1. A class to define an n-cube. It should support degenerate cubes and store their vertices, vertex boundary and generator information.
2. A class to define a 3D mesh. It should carry the relevant vertex coordinate, vertex normal and colour buffers. 

This is the overarching design that makes sense to me. Let me know if there are any Rust specific design considerations that I missed or any particular aspects that I should describe in more detail right now.

**Comment by jamievicary** [comment]
This sounds good to me, but it would be good to get confirmation from Nick/Lukas/Nathan.

Given that we won't have Calin's algorithm for a little while, could we start with a simpler cubicaliser, it doesn't matter if it leaves some holes in the geometry.

**Comment by zrho** [comment]
Sounds good. For storing the cubes and triangles there's an option to have the positions in a separate vector and index into that similarly to the vertex/index buffer split in OpenGL since for rendering we need the data in this shape anyway and can avoid the weirdness of comparing or hashing floats.

What is missing at the moment is layout for 3D. The layout algorithm currently implemented in `homotopy-graphics/layout2d.rs` can only produce 2D layouts and can't be trivially extended to deal with any higher dimensions: essentially it produces constraints for the coordinates and enforces the constraints in a loop until everything stabilises. We never got to actually proving that this always terminates but it always did. One can produce constraints of this form for higher dimensions as well, but already for 3D there are infeasible cases (in which the algorithm that we use for 2D diverges) so the constraints need to be relaxed. I've been solving these systems using an LP solver, but that turned out to be quite slow since the number of constraints becomes really large in higher dimensions and the structure of the system is unfortunate, so Jamie implemented some version which (if I understood it correctly) solves the 2D systems for the projections. That'd perhaps be an option again, but maybe there is some clever first order iterative solver we can hand roll: We can't quite use gradient descent since we have inequality constraints, but there's stuff like penalty methods that could be helpful (esp. since we need relaxed constraints anyway).

Minor comment: In Rust the classes are called structs, and we can have "free-floating" functions that are not associated to a struct in cases where that makes sense.

**Comment by NickHu** [comment]
I just wanted to expand a little on Lukas's comment about classes. Rust doesn't support true OOP (subtyping is missing). Instead it has *traits*, which are essentially the same thing as Haskell typeclasses. If you like, you can think of these as Java interfaces. These are the 'free floating' functions Lukas is talking about. It's just something to bear in mind if you wanted to use subtyping (you probably don't, as many years of OOP has taught us).
