### ISSUE TITLE
Order of contraction between invertible cells and homotopies

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#925]
In the following file I construct an example, where its source slice can be contract to identity by first smoothing the middle two homotopy, then annihilating a cell with its inverse; but when I fist contract the cell with a homotopy and then contract its inverse with another homotopy, I get the target slice and I am not allowed to further contract them. Is this the expected behaviour?

![Screenshot 2022-11-30 at 20 06 34](https://user-images.githubusercontent.com/35509721/204886520-3a6e2784-e396-49a3-bf49-40e8c8372e0c.png)
**Pic. of the source slice**

![Screenshot 2022-11-30 at 20 05 27](https://user-images.githubusercontent.com/35509721/204886333-c72b7226-b3fd-4d01-8a3d-c792e72f73c9.png)
**Pic. of the target slice**

**File:** 
[homotopy_io_export (1).hom.zip](https://github.com/homotopy-io/homotopy-rs/files/10126509/homotopy_io_export.1.hom.zip)

**Comment by calintat** [comment]
Yes, I think that's the expected behaviour because the contraction you're trying to do isn't well-typed.

**Comment by calintat** [comment]
The problem is that you're contracting the following diagram. What you want to do instead is **smooth** the middle homotopy. To do that, either drag up from regular 1 or drag down from regular 2 (but you need to click on the region between the two wires for it to work):

![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/206719116-02899f61-b8f0-4d80-93b3-0d40b6dd8806.svg)

Here is a proof that your diagram simplifies to the identity like you wanted: [homotopy_io_export.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/10195457/homotopy_io_export.hom.zip)
