### ISSUE TITLE
Crash when trying to save theorem

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#927]
In the attached .hom the tool crashes when I press Theorem. 
[88.zip](https://github.com/homotopy-io/homotopy-rs/files/10133228/88.zip)

**Comment by regular-citizen** [comment]
We verified that the panic handler works correctly in this case and no real panic occurred.
The problem is that this Theorem really takes too long to execute, due to collapse. I ran the example through homotopy-cli on my machine and in 12mins it still didn't complete.

So this is great for benchmarking but we don't think there is any bug here other than collapse being slow.

**Comment by jamievicary** [comment]
That is very interesting. We should revisit this when Nick has finished
optimizing collapse.
