### ISSUE TITLE
Layout crash

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#935]
This is a strange one. I was viewing 4d slices of the diagram below in 3d view, moving through slices from Target to Source by quickly pressing the the downwards arrow key. When I reached slice R30 the tool crashed.
[crash2.zip](https://github.com/homotopy-io/homotopy-rs/files/10156658/crash2.zip)
[unbraiding_fig8.zip](https://github.com/homotopy-io/homotopy-rs/files/10156662/unbraiding_fig8.zip)

**Comment by calintat** [comment]
Smaller counterexample: [homotopy_io_export(6).hom.zip](https://github.com/homotopy-io/homotopy-rs/files/10156768/homotopy_io_export.6.hom.zip)

Could be related to #816.

**Comment by calintat** [comment]
Here is an even simpler counterexample (a double braid on a cup and cap): [double_braid_cup_cap.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/10194262/double_braid_cup_cap.hom.zip)

The problem is that HiGHS returns an empty model even though the problem we're trying to solve is not empty.

@regular-citizen The reason we were getting a weird error is that your assertion here is debug only so isn't run on beta: https://github.com/homotopy-io/homotopy-rs/blob/a8b30c201ce989a37a3e070127b25952129800d0/homotopy-core/src/layout.rs#L404-L408

**Comment by calintat** [comment]
This also explains the HiGHS warning.
